[versions]
java = "25"
paper = "1.21.9-R0.1-SNAPSHOT"
configurate = "4.2.0"
litecommands = "3.11.0"
luckperms = "5.5"
worldedit = "7.4.5"
jetbrainsAnnotations = "26.1.0"
junit = "6.1.3"
assertj = "3.27.7"
palantir = "2.97.0"
spotless = "8.10.2"
runPaper = "3.1.0"

[libraries]
paper-api = { module = "io.papermc.paper:paper-api", version.ref = "paper" }
configurate-yaml = { module = "org.spongepowered:configurate-yaml", version.ref = "configurate" }
litecommands-bukkit = { module = "dev.rollczi:litecommands-bukkit", version.ref = "litecommands" }
litecommands-adventure = { module = "dev.rollczi:litecommands-adventure", version.ref = "litecommands" }
luckperms-api = { module = "net.luckperms:api", version.ref = "luckperms" }
worldedit-bukkit = { module = "com.sk89q.worldedit:worldedit-bukkit", version.ref = "worldedit" }
jetbrains-annotations = { module = "org.jetbrains:annotations", version.ref = "jetbrainsAnnotations" }
junit-bom = { module = "org.junit:junit-bom", version.ref = "junit" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher" }
assertj-core = { module = "org.assertj:assertj-core", version.ref = "assertj" }
spotless-plugin = { module = "com.diffplug.spotless:spotless-plugin-gradle", version.ref = "spotless" }

[plugins]
run-paper = { id = "xyz.jpenilla.run-paper", version.ref = "runPaper" }
